name: flutter_instagram_stories
homepage: https://github.com/awaik/flutter_instagram_stories
description: Display stories just like Whatsapp & Instagram. Built-in groups (multiple stories with one icon), cache, video, gifs. For now works with Firestore database only.
version: 0.1.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.1.3
  rxdart: ^0.23.1
  video_player: ^0.10.5
  cached_network_image: ^2.0.0
  json_annotation: ^3.0.1
  skeleton_text: ^1.0.0
  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.13.0+1

dev_dependencies:
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  test: ^1.6.1
