name: flutter_instagram_stories
homepage: https://github.com/awaik/flutter_instagram_stories
description: Display stories (videos and images) like Whatsapp & Instagram.
version: 0.1.5+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^2.0.0
  rxdart: ^0.24.1
  video_player: ^0.11.1+2
  cached_network_image: ^2.3.3
  json_annotation: ^3.1.0
  skeleton_text: ^1.0.0
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  dotted_border: ^1.0.6

dev_dependencies:
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  test: ^1.15.4
