name: flutter_instagram_stories
author: awaik <awaiking44@gmail.com>
homepage: https://github.com/awaik/flutter_instagram_stories
description: Display stories just like Whatsapp & Instagram. Can be used inline/inside ListView or Column just like Google News app. Comes with gestures to pause, forward & go to previous page.
version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.1.3
  rxdart: ^0.23.1
  video_player: ^0.10.5
  cached_network_image: ^2.0.0
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  test: ^1.6.1
